name: Check if PR is linked with an Azure Board Story

on: 
  pull_request:
    types: [opened, edited]

jobs:
  run-ab-story-validation:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: emagers/ab-story-validation-action@main
        
