name: ADO PR Check

on: 
  pull_request:
    types: [opened, edited]

jobs:
  run-ab-story-validation:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Check if an Azure Boards work item is mentioned in the PR Body
      id: pr-body-extract
      uses: actions/github-script@v6
      with:
        script: |
          const prBody = context.payload.pull_request.body;
          const adoItem = prBody.match(/AB\#(\d)+/g);
          return adoItem[0]
        result-encoding: string
    - name: Show result
      run: echo "${{steps.pr-body-extract.outputs.result}}"
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
