name: ADO PR Check

on: 
  pull_request:
    types: [opened, edited]

jobs:
  run-ab-story-validation:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Check if an Azure Boards work item is mentioned in the PR Body
      uses: actions/variable-regex-extractor-action@v1.1
      with:
        pattern: |
          `/AB\#(\d)+/g`
        
