name: ADO PR Check

on: 
  pull_request:
    types: [opened, edited]

jobs:
  run-ab-story-validation:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: MarcinGadomski94/pr-update-work-item-state@master
      env: 
        gh_token : '${{ secrets.GH_TOKEN }}'   
        ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
        ado_organization: '${{ secrets.ADO_ORGANIZATION }}'
        ado_project: '${{ secrets.ADO_PROJECT }}'
        closedstate: 'Done'
        propenstate: 'Ready'
        inprogressstate: 'In Progress' 
        gh_repo_owner: 'repo-ctrl'
        gh_repo: 'azure-boards-integration-repo'
        pull_number: '${{github.event.number}}' 
        branch_name: '${{ github.ref }}'
        
